#!/usr/bin/env php
<?php

if ($argc < 2) {
    die("usage: bump_version <version-id>\n");
}

$json = json_decode(file_get_contents('gini.json'));
if (!$json) {
    die("invalid gini.json!\n");
}

$old_version = $json->version;
$json->version = $argv[1];

file_put_contents('gini.json', json_encode($json, JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT));
echo "bumped version from $old_version to $json->version\n";
