<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title><?php echo $title ? H($title) : ''; ?></title>
	<meta http-equiv="Content-Style-Type" content="text/css" />
	<meta http-equiv="Content-Script-Type" content="text/javascript" />
	<base href="<?php echo \Model\URI::base(); ?>" />
	<style>
		body { background-color: #693; padding: 0 1em 1em; font-family: helvetica;}
		h1 { text-align: center; color: #fff;}
		div.body h3 { color: #360;}
		div.body { background-color: #fff; width: 800px; margin: 0 auto; padding: 1em 2em; border-radius:.5em;}
		div.footer { padding-top: 1em; color: #cfc; text-align: center;}
		.monospace {font-family: monospace;}
	</style>
</head>
<body>
	<?php echo $this->body; ?>
</body>
</html>
