<h1><a href="<?php e(URL()); ?>"><?php eH(T('Gini PHP Framework')); ?></a></h1>
<div class="body">
	<h3><?php eH(T('Hello, world!')); ?></h3>
	<p><?php eH(T('Please override this view')); ?>: <strong><?php eH(__FILE__); ?></strong></p>
	<div class="monospace">
		<div><strong>SYS_PATH</strong> = <?php eH(SYS_PATH); ?></div>
		<div><strong>APP_PATH</strong> = <?php eH(APP_PATH); ?></div>
	</div>
</div>
<div class="footer">
	2012 &copy; <?php eH(T('Jia Huang from Genee')); ?>
</div>