<h1><a href="<?= URL() ?>"><?= H(T('Gini PHP Framework')) ?></a></h1>
<div class="body">
	<h3><?= H(T('Hello, world!')) ?></h3>
	<p><?= H(T('Please override this view')) ?>: <strong><?= H(__FILE__) ?></strong></p>
	<div class="monospace">
		<div><strong>SYS_PATH</strong> = <?= H(SYS_PATH) ?></div>
		<div><strong>APP_PATH</strong> = <?= H(APP_PATH) ?></div>
	</div>
</div>
<div class="footer">
	2012 &copy; <?= H(T('Jia Huang from Genee')) ?>
</div>