<?php if (count($tabs) > 0): ?>
<div class="tabs_container_wrapper<?php echo $class?' '.$class:''?>"><div class="tabs_container">
	<span class="tabs">
		<span class="tabs_body"><span class="tabs_content">
<?php foreach($tabs as $tab): 
		if (isset($tab['*'])) {
			$links = array();
			foreach ($tab['*'] as $t) {
				$links[]= URI::anchor($t['url'], $t['title'], 'class="middle"');
			}
			$content = implode(' <span class="separator middle">►</span> ', $links);
		}
		else {
			$content = URI::anchor($tab['url'], $tab['title'], 'class="middle"');
		}
		?><span class="tab_wrapper"><span class="tab<?php echo $tab['active']?' active_tab':''?>"><?php echo $content ?></span><?php 
				if($tab['number']): 
					$len = strlen($tab['number']);
				?><span class="tab_superscript num_notif num_notif_<?php echo $len;?>"><?php echo $tab['number'] ?></span><?php 
				endif; 
			?></span><?php 
			endforeach; ?>
		</span></span>
	</span>
</div></div>
<?php endif; 

