<h1><a href="<?= URL() ?>"><?= H('Gini PHP Framework') ?></a></h1>
<div class="body">
    <h3><?= H('Hello, world!') ?></h3>
    <p><?= H('Please override this view') ?>: <strong><?= H(__FILE__) ?></strong></p>
    <div class="monospace">
        <div><strong>SYS_PATH</strong> = <?= H(SYS_PATH) ?></div>
        <div><strong>APP_PATH</strong> = <?= H(APP_PATH) ?></div>
    </div>
</div>
<div class="footer">
    <?= date('Y')?> &copy; <?= H('Jia Huang from Genee') ?>
</div>